# Generated by Django 6.0.2 on 2026-03-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=40, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono')),
                ('cajero', models.ForeignKey(blank=True, db_column='ID_Usr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='usuarios.cajero', verbose_name='Cajero')),
            ],
        ),
    ]
