# Generated by Django 6.0.2 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(db_column='Nombre_Completo', max_length=40, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, db_column='Telefono', max_length=14, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
    ]
