# Generated by Django 6.0.2 on 2026-03-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Número de Documento'),
        ),
    ]
