# Generated by Django 6.0.2 on 2026-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_id_alter_cliente_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=40, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
