# Generated by Django 6.0.2 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_id_alter_cliente_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Número de Documento'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
    ]
