# Generated by Django 6.0.2 on 2026-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_id_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Número de Documento'),
        ),
    ]
