# Generated by Django 6.0.2 on 2026-03-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('cantidad', models.SmallIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('categoria', models.CharField(blank=True, choices=[('Hamburguesas', 'Hamburguesas'), ('Perros Calientes', 'Perros Calientes'), ('Entradas y Snacks', 'Entradas y Snacks'), ('Combos', 'Combos'), ('Bebidas', 'Bebidas'), ('Postres', 'Postres'), ('Adiciones', 'Adiciones'), ('Salsas', 'Salsas')], max_length=20, null=True, verbose_name='Categoría')),
            ],
        ),
    ]
