# Generated by Django 6.0.2 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveSmallIntegerField(db_column='Cantidad', default=0, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Hamburguesas', 'Hamburguesas'), ('Perros Calientes', 'Perros Calientes'), ('Entradas y Snacks', 'Entradas y Snacks'), ('Combos', 'Combos'), ('Bebidas', 'Bebidas'), ('Postres', 'Postres'), ('Adiciones', 'Adiciones'), ('Salsas', 'Salsas')], db_column='Categoria', max_length=20, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(db_column='Nombre_Producto', max_length=50, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(db_column='Precio', verbose_name='Precio'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
