# Generated by Django 6.0.2 on 2026-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_cantidad_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.SmallIntegerField(default=0, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Hamburguesas', 'Hamburguesas'), ('Perros Calientes', 'Perros Calientes'), ('Entradas y Snacks', 'Entradas y Snacks'), ('Combos', 'Combos'), ('Bebidas', 'Bebidas'), ('Postres', 'Postres'), ('Adiciones', 'Adiciones'), ('Salsas', 'Salsas')], max_length=20, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
