# Generated by Django 6.0.2 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_cantidad_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
