# Generated by Django 6.0.2 on 2026-03-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(db_column='id', max_length=16, primary_key=True, serialize=False, verbose_name='Documento')),
                ('telefono', models.CharField(max_length=14, verbose_name='Teléfono')),
                ('contraseña', models.CharField(db_column='contraseña', max_length=20, verbose_name='Contraseña')),
                ('correo_electronico', models.EmailField(db_column='correo_electronico', max_length=35, verbose_name='Correo Electrónico')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Vacaciones', 'Vacaciones'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nombre_completo', models.CharField(max_length=40, verbose_name='Nombre Completo')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('experiencia_laboral', models.CharField(max_length=100, verbose_name='Experiencia Laboral')),
            ],
            options={
                'db_table': 'usuarios_usuario',
            },
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_reservas', models.PositiveIntegerField(default=50, verbose_name='Meta de Reservas')),
                ('meta_pedidos', models.PositiveIntegerField(default=200, verbose_name='Meta de Pedidos')),
            ],
            options={
                'db_table': 'DashboardConfig',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(db_column='ID_Usr', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrador', serialize=False, to='usuarios.usuario')),
                ('ultima_fecha_login', models.DateTimeField(blank=True, db_column='Ult_Fecha_login', null=True, verbose_name='Última Fecha de Login')),
                ('formacion_educativa', models.CharField(blank=True, db_column='Formacion_Educativa', max_length=35, null=True, verbose_name='Formación Educativa')),
            ],
            options={
                'db_table': 'usuarios_administrador',
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('usuario', models.OneToOneField(db_column='ID_Usr', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cajero', serialize=False, to='usuarios.usuario')),
                ('eps', models.CharField(blank=True, choices=[('Nueva EPS', 'Nueva EPS'), ('Sanitas', 'Sanitas'), ('SURA', 'SURA'), ('Salud Total', 'Salud Total'), ('Compensar', 'Compensar'), ('Famisanar', 'Famisanar'), ('Coosalud', 'Coosalud'), ('Mutual Ser', 'Mutual Ser'), ('SOS', 'SOS'), ('Salud Mía', 'Salud Mía'), ('Aliansalud', 'Aliansalud'), ('Dusakawi', 'Dusakawi'), ('Salud Bolívar', 'Salud Bolívar'), ('Savia Salud', 'Savia Salud'), ('Cajacopi', 'Cajacopi'), ('Asmet Salud', 'Asmet Salud'), ('Emssanar', 'Emssanar'), ('Capital Salud', 'Capital Salud')], db_column='EPS', max_length=20, null=True, verbose_name='EPS')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Fijo')], db_column='tipo_contrato', max_length=10, null=True, verbose_name='Tipo de Contrato')),
                ('turno', models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], db_column='Turno', max_length=7, null=True, verbose_name='Turno')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, db_column='Contacto_Emergencia_Nombre', max_length=35, null=True, verbose_name='Nombre Contacto Emergencia')),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, db_column='Contacto_Emergencia_Parentesco', max_length=15, null=True, verbose_name='Parentesco Contacto Emergencia')),
                ('contacto_emergencia_numero', models.CharField(blank=True, db_column='Contacto_Emergencia_Numero', max_length=14, null=True, verbose_name='Número Contacto Emergencia')),
                ('fecha_terminacion_contrato', models.DateField(blank=True, db_column='Fecha_Terminacion_Contrato', null=True, verbose_name='Fecha Terminación Contrato')),
            ],
            options={
                'db_table': 'usuarios_cajero',
            },
        ),
    ]
