# Generated by Django 6.0.2 on 2026-03-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(db_column='id', max_length=16, primary_key=True, serialize=False, verbose_name='Documento')),
                ('telefono', models.CharField(max_length=14, verbose_name='Teléfono')),
                ('contraseña', models.CharField(db_column='contraseña', max_length=20, verbose_name='Contraseña')),
                ('correo_electronico', models.EmailField(db_column='correo_electronico', max_length=35, verbose_name='Correo Electrónico')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nombre_completo', models.CharField(max_length=40, verbose_name='Nombre Completo')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('experiencia_laboral', models.CharField(max_length=15, verbose_name='Experiencia Laboral')),
            ],
            options={
                'db_table': 'usuarios_usuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrador', serialize=False, to='usuarios.usuario')),
                ('ultima_fecha_login', models.DateTimeField(blank=True, null=True, verbose_name='Última Fecha de Login')),
                ('formacion_educativa', models.CharField(blank=True, max_length=35, null=True, verbose_name='Formación Educativa')),
            ],
            options={
                'db_table': 'usuarios_administrador',
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('usuario', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cajero', serialize=False, to='usuarios.usuario')),
                ('eps', models.CharField(blank=True, max_length=20, null=True, verbose_name='EPS')),
                ('tipo_contrato', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Contrato')),
                ('turno', models.CharField(blank=True, max_length=7, null=True, verbose_name='Turno')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=35, null=True)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_emergencia_numero', models.CharField(blank=True, max_length=14, null=True)),
                ('fecha_terminacion_contrato', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_cajero',
            },
        ),
    ]
