# Generated by Django 6.0.2 on 2026-03-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='ultima_fecha_login',
        ),
        migrations.AddField(
            model_name='administrador',
            name='ult_fecha_login',
            field=models.DateTimeField(blank=True, db_column='Ult_Fecha_login', null=True, verbose_name='Última Fecha de Login'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='ult_ip_login',
            field=models.CharField(blank=True, db_column='Ult_IP_login', max_length=45, null=True, verbose_name='Última IP de Login'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='formacion_educativa',
            field=models.CharField(blank=True, db_column='Formacion_Educativa', max_length=35, null=True, verbose_name='Formación Educativa'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(db_column='ID_Usr', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrador', serialize=False, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Nombre', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_numero',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Numero', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Parentesco', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='eps',
            field=models.CharField(blank=True, choices=[('Nueva EPS', 'Nueva EPS'), ('Sanitas', 'Sanitas'), ('SURA', 'SURA'), ('Salud Total', 'Salud Total'), ('Compensar', 'Compensar'), ('Famisanar', 'Famisanar'), ('Coosalud', 'Coosalud'), ('Mutual Ser', 'Mutual Ser'), ('SOS', 'SOS'), ('Salud Mía', 'Salud Mía'), ('Aliansalud', 'Aliansalud'), ('Dusakawi', 'Dusakawi'), ('Salud Bolívar', 'Salud Bolívar'), ('Savia Salud', 'Savia Salud'), ('Cajacopi', 'Cajacopi'), ('Asmet Salud', 'Asmet Salud'), ('Emssanar', 'Emssanar'), ('Capital Salud', 'Capital Salud')], db_column='EPS', max_length=20, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='fecha_terminacion_contrato',
            field=models.DateField(blank=True, db_column='Fecha_Terminacion_Contrato', null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Fijo')], db_column='tipo_contrato', max_length=10, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='turno',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], db_column='Turno', max_length=7, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='usuario',
            field=models.OneToOneField(db_column='ID_Usr', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cajero', serialize=False, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(db_column='Contraseña', max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(db_column='Correo_Electronico', max_length=35, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(db_column='Direccion', max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Vacaciones', 'Vacaciones'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='experiencia_laboral',
            field=models.CharField(db_column='Experiencia_Laboral', max_length=15, verbose_name='Experiencia Laboral'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(db_column='Fecha_ingreso', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(db_column='Fecha_Nacimiento', verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.CharField(db_column='ID', max_length=16, primary_key=True, serialize=False, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(db_column='Nombre_Completo', max_length=40, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(db_column='Telefono', max_length=14, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='Administrador',
        ),
        migrations.AlterModelTable(
            name='cajero',
            table='Cajero',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
