# Generated by Django 6.0.2 on 2026-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_administrador_ultima_fecha_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='ult_fecha_login',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='ult_ip_login',
        ),
        migrations.AddField(
            model_name='administrador',
            name='ultima_fecha_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Fecha de Login'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='formacion_educativa',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Formación Educativa'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_numero',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='eps',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='fecha_terminacion_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='turno',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(db_column='contraseña', max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(db_column='correo_electronico', max_length=35, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='Activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='experiencia_laboral',
            field=models.CharField(max_length=15, verbose_name='Experiencia Laboral'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.CharField(db_column='id', max_length=16, primary_key=True, serialize=False, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=40, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=14, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='usuarios_administrador',
        ),
        migrations.AlterModelTable(
            name='cajero',
            table='usuarios_cajero',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios_usuario',
        ),
    ]
