# Generated by Django 6.0.2 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_administrador_ult_fecha_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='ultima_ip_login',
            field=models.CharField(blank=True, db_column='Ult_IP_login', max_length=45, null=True, verbose_name='Última IP de Login'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='formacion_educativa',
            field=models.CharField(blank=True, db_column='Formacion_Educativa', max_length=35, null=True, verbose_name='Formación Educativa'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='ultima_fecha_login',
            field=models.DateTimeField(blank=True, db_column='Ult_Fecha_login', null=True, verbose_name='Última Fecha de Login'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Nombre', max_length=35, null=True, verbose_name='Nombre Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_numero',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Numero', max_length=14, null=True, verbose_name='Número Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Parentesco', max_length=15, null=True, verbose_name='Parentesco Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='eps',
            field=models.CharField(blank=True, choices=[('Nueva EPS', 'Nueva EPS'), ('Sanitas', 'Sanitas'), ('SURA', 'SURA'), ('Salud Total', 'Salud Total'), ('Compensar', 'Compensar'), ('Famisanar', 'Famisanar'), ('Coosalud', 'Coosalud'), ('Mutual Ser', 'Mutual Ser'), ('SOS', 'SOS'), ('Salud Mía', 'Salud Mía'), ('Aliansalud', 'Aliansalud'), ('Dusakawi', 'Dusakawi'), ('Salud Bolívar', 'Salud Bolívar'), ('Savia Salud', 'Savia Salud'), ('Cajacopi', 'Cajacopi'), ('Asmet Salud', 'Asmet Salud'), ('Emssanar', 'Emssanar'), ('Capital Salud', 'Capital Salud')], db_column='EPS', max_length=20, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='fecha_terminacion_contrato',
            field=models.DateField(blank=True, db_column='Fecha_Terminacion_Contrato', null=True, verbose_name='Fecha Terminación Contrato'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Fijo')], db_column='tipo_contrato', max_length=10, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='turno',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], db_column='Turno', max_length=7, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Vacaciones', 'Vacaciones'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
    ]
