# Generated by Django 6.0.2 on 2026-03-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_administrador_ultima_ip_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='ultima_ip_login',
        ),
    ]
