# Generated by Django 6.0.2 on 2026-03-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_administrador_ultima_ip_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='experiencia_laboral',
            field=models.CharField(max_length=100, verbose_name='Experiencia Laboral'),
        ),
    ]
