# Generated by Django 6.0.2 on 2026-03-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_experiencia_laboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_reservas', models.PositiveIntegerField(default=50, verbose_name='Meta de Reservas')),
                ('meta_pedidos', models.PositiveIntegerField(default=200, verbose_name='Meta de Pedidos')),
            ],
            options={
                'db_table': 'DashboardConfig',
            },
        ),
    ]
