# Generated by Django 6.0.2 on 2026-03-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('cajero', models.ForeignKey(blank=True, db_column='ID_Usr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='usuarios.cajero', verbose_name='Cajero')),
            ],
        ),
    ]
