# Generated by Django 6.0.2 on 2026-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
