# Generated by Django 6.0.2 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(db_column='Estado', default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(db_column='Fecha', verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, db_column='Observciones', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='Reserva',
        ),
    ]
