# Generated by Django 6.0.2 on 2026-04-22 21:10

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(validators=[reservas.models.validate_future_date], verbose_name='Fecha y Hora'),
        ),
    ]
