# Generated by Django 6.0.2 on 2026-03-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_id'),
        ('reservas', '0004_alter_reserva_id_alter_reserva_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='ID_Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
