# Generated by Django 6.0.2 on 2026-03-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia_prima', models.CharField(max_length=60, verbose_name='Nombre')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
                ('cantidad', models.SmallIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProductoMateriaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.SmallIntegerField(default=0, verbose_name='Cantidad Usada')),
                ('producto', models.ForeignKey(db_column='Producto_ID', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_materia', to='productos.producto', verbose_name='Producto')),
                ('materia_prima', models.ForeignKey(db_column='MateriaPrima_ID', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='materia_prima.materiaprima', verbose_name='Materia Prima')),
            ],
        ),
    ]
