# Generated by Django 6.0.2 on 2026-03-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia_prima', models.CharField(max_length=60, verbose_name='Nombre')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
                ('cantidad_por_unidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad por Unidad')),
                ('tipo', models.CharField(choices=[('Comida', 'Comida'), ('Bebida', 'Bebida')], default='Comida', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'db_table': 'Materia_Prima',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.PositiveIntegerField(verbose_name='Cantidad Recibida')),
                ('cantidad_actual', models.PositiveIntegerField(verbose_name='Cantidad Disponible')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio x Unidad')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='materia_prima.materiaprima')),
            ],
            options={
                'db_table': 'Lote_Materia_Prima',
                'ordering': ['fecha_vencimiento', 'fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductoMateriaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad Usada')),
                ('producto', models.ForeignKey(db_column='Producto_ID', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_materia', to='productos.producto', verbose_name='Producto')),
                ('materia_prima', models.ForeignKey(db_column='MateriaPrima_ID', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='materia_prima.materiaprima', verbose_name='Materia Prima')),
            ],
            options={
                'db_table': 'Details_Producto_MateriaP',
                'unique_together': {('producto', 'materia_prima')},
            },
        ),
    ]
