# Generated by Django 6.0.2 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductomateriap',
            name='cantidad_usada',
            field=models.PositiveSmallIntegerField(db_column='Cantidad_Usada', default=0, verbose_name='Cantidad Usada'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.PositiveSmallIntegerField(db_column='Cantidad', default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, db_column='Fecha_Ingreso', null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_column='Fecha_Vencimiento', null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='nombre_materia_prima',
            field=models.CharField(db_column='Nombre_Materia_Prima', max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(blank=True, db_column='Unidad_Medida', max_length=20, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterModelTable(
            name='detalleproductomateriap',
            table='Details_Producto_MateriaP',
        ),
        migrations.AlterModelTable(
            name='materiaprima',
            table='Materia_Prima',
        ),
    ]
