# Generated by Django 6.0.2 on 2026-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0002_alter_detalleproductomateriap_cantidad_usada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductomateriap',
            name='cantidad_usada',
            field=models.SmallIntegerField(default=0, verbose_name='Cantidad Usada'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.SmallIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='nombre_materia_prima',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterModelTable(
            name='detalleproductomateriap',
            table=None,
        ),
        migrations.AlterModelTable(
            name='materiaprima',
            table=None,
        ),
    ]
