# Generated by Django 6.0.2 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0003_alter_detalleproductomateriap_cantidad_usada_and_more'),
        ('productos', '0004_alter_producto_cantidad_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductomateriap',
            name='cantidad_usada',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad Usada'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleproductomateriap',
            unique_together={('producto', 'materia_prima')},
        ),
        migrations.AlterModelTable(
            name='detalleproductomateriap',
            table='Details_Producto_MateriaP',
        ),
        migrations.AlterModelTable(
            name='materiaprima',
            table='Materia_Prima',
        ),
    ]
