# Generated by Django 6.0.2 on 2026-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0004_alter_detalleproductomateriap_cantidad_usada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
