# Generated by Django 6.0.2 on 2026-03-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0005_alter_materiaprima_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Stock Base (Obsoleto)'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso Base'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento Base'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Recibida')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Disponible')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio x Unidad')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='materia_prima.materiaprima')),
            ],
            options={
                'db_table': 'Lote_Materia_Prima',
                'ordering': ['fecha_vencimiento', 'fecha_ingreso'],
            },
        ),
    ]
