# Generated by Django 6.0.2 on 2026-03-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0006_alter_materiaprima_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='fecha_vencimiento',
        ),
    ]
