# Generated by Django 6.0.2 on 2026-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0007_remove_materiaprima_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='tipo',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Bebida', 'Bebida')], default='Comida', max_length=10, verbose_name='Tipo'),
        ),
    ]
