# Generated by Django 6.0.2 on 2026-03-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0008_materiaprima_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad_por_unidad',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cantidad por Unidad'),
        ),
    ]
