# Generated by Django 6.0.2 on 2026-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0009_materiaprima_cantidad_por_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cantidad_actual',
            field=models.PositiveIntegerField(verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad_inicial',
            field=models.PositiveIntegerField(verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad_por_unidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad por Unidad'),
        ),
    ]
