# Generated by Django 6.0.2 on 2026-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0011_detalleproductomateriap_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductomateriap',
            name='cantidad_usada',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Usada'),
        ),
    ]
