# Generated by Django 6.0.2 on 2026-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0012_alter_detalleproductomateriap_cantidad_usada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductomateriap',
            name='cantidad_usada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Usada'),
        ),
        migrations.AlterField(
            model_name='detalleproductomateriap',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad Usada'),
        ),
    ]
