# Generated by Django 6.0.2 on 2026-03-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.PositiveIntegerField(verbose_name='Valor Total')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('iva', models.FloatField(blank=True, null=True, verbose_name='IVA (%)')),
                ('pedido', models.ForeignKey(db_column='ID_Pedi', on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
    ]
