# Generated by Django 6.0.2 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.FloatField(blank=True, db_column='IVA', null=True, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='valor_total',
            field=models.PositiveIntegerField(db_column='Valor_Total', verbose_name='Valor Total'),
        ),
        migrations.AlterModelTable(
            name='factura',
            table='Factura',
        ),
    ]
