# Generated by Django 6.0.2 on 2026-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_factura_descripcion_alter_factura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.FloatField(blank=True, null=True, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='valor_total',
            field=models.PositiveIntegerField(verbose_name='Valor Total'),
        ),
        migrations.AlterModelTable(
            name='factura',
            table=None,
        ),
    ]
