# Generated by Django 6.0.2 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_factura_descripcion_alter_factura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='factura',
            table='Factura',
        ),
    ]
