# Generated by Django 6.0.2 on 2026-03-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('materia_prima', '0001_initial'),
        ('productos', '0001_initial'),
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor Total')),
                ('numero_orden', models.PositiveSmallIntegerField(verbose_name='Número de Orden')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('PSE', 'PSE')], max_length=16, verbose_name='Método de Pago')),
                ('cajero', models.ForeignKey(blank=True, db_column='ID_Usr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.cajero', verbose_name='Cajero')),
                ('cliente', models.ForeignKey(blank=True, db_column='ID_Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('reserva', models.ForeignKey(blank=True, db_column='ID_Reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.PositiveIntegerField(verbose_name='Precio Unitario')),
                ('estado', models.CharField(choices=[('preparando', 'preparando'), ('finalizado', 'finalizado')], default='preparando', max_length=10, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notas/Modificaciones')),
                ('materias_excluidas', models.ManyToManyField(blank=True, related_name='excluidas_en_pedidos', to='materia_prima.materiaprima', verbose_name='Materias Excluidas')),
                ('producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='productos.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(db_column='ID_Pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'db_table': 'Details_Pedido_Producto',
            },
        ),
    ]
