# Generated by Django 6.0.2 on 2026-04-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Preparacion', 'En preparación'), ('Completado', 'Completado')], default='Registrado', max_length=12, verbose_name='Estado'),
        ),
    ]
