# Generated by Django 6.0.2 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='cantidad',
            field=models.PositiveSmallIntegerField(db_column='Cantidad', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='estado',
            field=models.CharField(choices=[('preparando', 'preparando'), ('finalizado', 'finalizado')], db_column='Estado', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='precio_unitario',
            field=models.PositiveIntegerField(db_column='Precio_Unitario', verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(db_column='Estado', default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(db_column='Fecha', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('PSE', 'PSE')], db_column='Metodo_Pago', max_length=16, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_orden',
            field=models.PositiveSmallIntegerField(db_column='numero_orden', verbose_name='Número de Orden'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.PositiveIntegerField(db_column='Valor', verbose_name='Valor Total'),
        ),
        migrations.AlterModelTable(
            name='detallepedidoproducto',
            table='Details_Pedido_Producto',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='Pedido',
        ),
    ]
