# Generated by Django 6.0.2 on 2026-04-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Preparacion', 'En preparación'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Preparacion', max_length=12, verbose_name='Estado'),
        ),
    ]
