# Generated by Django 6.0.2 on 2026-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_detallepedidoproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='cantidad',
            field=models.SmallIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='estado',
            field=models.CharField(choices=[('preparando', 'Preparando'), ('finalizado', 'Finalizado')], default='preparando', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='precio_unitario',
            field=models.PositiveIntegerField(verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('PSE', 'PSE')], max_length=16, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_orden',
            field=models.SmallIntegerField(verbose_name='Número de Orden'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.PositiveIntegerField(verbose_name='Valor Total'),
        ),
        migrations.AlterModelTable(
            name='detallepedidoproducto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
    ]
