# Generated by Django 6.0.2 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_detallepedidoproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='cantidad',
            field=models.PositiveSmallIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='estado',
            field=models.CharField(choices=[('preparando', 'preparando'), ('finalizado', 'finalizado')], default='preparando', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_orden',
            field=models.PositiveSmallIntegerField(verbose_name='Número de Orden'),
        ),
        migrations.AlterModelTable(
            name='detallepedidoproducto',
            table='Details_Pedido_Producto',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='Pedido',
        ),
    ]
