# Generated by Django 6.0.2 on 2026-04-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_estado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cajero',
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='ID_Usr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.usuario', verbose_name='Registrado por'),
        ),
    ]
