# Generated by Django 6.0.2 on 2026-04-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_cajero_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('Bancolombia a la Mano', 'Bancolombia a la Mano'), ('RappiPay', 'RappiPay'), ('Movii', 'Movii'), ('Dale', 'Dale'), ('PSE', 'PSE'), ('Transferencia', 'Transferencia'), ('Otros', 'Otros')], max_length=40, verbose_name='Método de Pago'),
        ),
    ]
