# Generated by Django 6.0.2 on 2026-03-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0006_alter_materiaprima_cantidad_and_more'),
        ('pedidos', '0005_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedidoproducto',
            name='materias_excluidas',
            field=models.ManyToManyField(blank=True, related_name='excluidas_en_pedidos', to='materia_prima.materiaprima', verbose_name='Materias Excluidas'),
        ),
        migrations.AddField(
            model_name='detallepedidoproducto',
            name='notas',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Notas/Modificaciones'),
        ),
    ]
