# Generated by Django 6.0.2 on 2026-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_detallepedidoproducto_materias_excluidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
    ]
