# Generated by Django 6.0.2 on 2026-03-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia_prima', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50, verbose_name='Nombre del Proveedor')),
                ('direccion', models.CharField(blank=True, max_length=120, null=True, verbose_name='Dirección')),
                ('correo_electronico', models.EmailField(blank=True, max_length=35, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono')),
                ('cajero', models.ForeignKey(blank=True, db_column='ID_Usr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='usuarios.cajero', verbose_name='Cajero')),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetalleProveedorMateriaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario')),
                ('fecha_suministro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Suministro')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('materia_prima', models.ForeignKey(db_column='MateriaPrima_ID', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_proveedor', to='materia_prima.materiaprima', verbose_name='Materia Prima')),
                ('proveedor', models.ForeignKey(db_column='Proveedor_ID', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_materia', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'db_table': 'Details_Proveedor_MateriaP',
            },
        ),
    ]
