# Generated by Django 6.0.2 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproveedormateriap',
            name='fecha_suministro',
            field=models.DateTimeField(blank=True, db_column='Fecha_Suministro', null=True, verbose_name='Fecha de Suministro'),
        ),
        migrations.AlterField(
            model_name='detalleproveedormateriap',
            name='precio_unitario',
            field=models.DecimalField(blank=True, db_column='Precio_Unitario', decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, db_column='Correo_Electronico', max_length=35, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, db_column='Direccion', max_length=120, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(db_column='Nombre_Proveedor', max_length=50, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, db_column='Telefono', max_length=14, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='detalleproveedormateriap',
            table='Details_Proveedor_MateriaP',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedor',
        ),
    ]
