# Generated by Django 6.0.2 on 2026-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_detalleproveedormateriap_fecha_suministro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproveedormateriap',
            name='fecha_suministro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Suministro'),
        ),
        migrations.AlterField(
            model_name='detalleproveedormateriap',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=35, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=50, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='detalleproveedormateriap',
            table=None,
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
    ]
