# Generated by Django 6.0.2 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0004_alter_detalleproductomateriap_cantidad_usada_and_more'),
        ('proveedores', '0003_alter_detalleproveedormateriap_fecha_suministro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleproveedormateriap',
            unique_together={('proveedor', 'materia_prima')},
        ),
        migrations.AlterModelTable(
            name='detalleproveedormateriap',
            table='Details_Proveedor_MateriaP',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedor',
        ),
    ]
