# Generated by Django 6.0.2 on 2026-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_proveedor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproveedormateriap',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
