# Generated by Django 6.0.2 on 2026-03-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_detalleproveedormateriap_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleproveedormateriap',
            unique_together=set(),
        ),
    ]
